name: Build Go Chatroom

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [386, amd64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
          GOARCH: ${{ matrix.arch }}
        run: |
          output_name="go-chatroom"
          if [ "$GOOS" = "windows" ]; then
            output_name="$output_name.exe"
          fi
          go build -o "bin/$GOOS-$GOARCH/$output_name" .
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-chatroom-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}-${{ matrix.arch }}/
